# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'chillmate' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

    # this is very important to have!
    rn_path = '../node_modules/react-native'
    pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
    pod 'React', path: rn_path, subspecs: [
      'Core',
      'RCTActionSheet',
      'RCTAnimation',
      'RCTGeolocation',
      'RCTImage',
      'RCTLinkingIOS',
      'RCTNetwork',
      'RCTSettings',
      'RCTText',
      'RCTVibration',
      'RCTWebSocket'
    ]

  # Pods for chillmate

  pod 'GoogleSignIn', '~> 4.4.0'

  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.20.1'

  pod 'Firebase/Functions', '~> 5.20.1'

  Pod

  pod 'Firebase/Auth', '~> 5.20.1'

  pod 'Firebase/Messaging', '~> 5.20.1'

  pod 'Firebase/Database', '~> 5.20.1'

  pod 'Firebase/Storage', '~> 5.20.2'

  pod 'GoogleIDFASupport', '~> 3.14.0'

  pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'


  pod 'RNSha256', :path => '../node_modules/react-native-sha256'

  target 'chillmateTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# very important to have, unless you removed React dependencies for Libraries
# and you rely on Cocoapods to manage it
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end

target 'chillmate-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for chillmate-tvOS

  target 'chillmate-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
