# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'chillmate' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for chillmate

  pod 'GoogleSignIn', '~> 4.4.0'

  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.20.1'

  pod 'Firebase/Functions', '~> 5.20.1'

  pod 'Firebase/Auth', '~> 5.20.1'

  pod 'Firebase/Messaging', '~> 5.20.1'

  pod 'Firebase/Database', '~> 5.20.1'

  target 'chillmateTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'chillmate-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for chillmate-tvOS

  target 'chillmate-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
